export const scoreCodes = {
	'0': 'Civil Rights',
	'1': 'Economy',
	'2': 'Political Freedoms',
	'3': 'Population',
	'4': 'Wealth Gaps',
	'5': 'Death Rate',
	'6': 'Compassion',
	'7': 'Eco',
	'8': 'Social Conservatism',
	'9': 'Nudity',
	'10': 'Industry: Automobile Manufacturing',
	'11': 'Industry: Cheese Exports',
	'12': 'Industry: Basket Weaving',
	'13': 'Industry: Informtion Technology',
	'14': 'Industry: Pizza Delivery',
	'15': 'Industry: Trout Fishing',
	'16': 'Industry: Arms Manufacturing',
	'17': 'Sector: Agriculture',
	'18': 'Industry: Beverage Sales',
	'19': 'Industry: Timber Woodchipping',
	'20': 'Industry: Mining',
	'21': 'Industry: Insurance',
	'22': 'Industry: Furniture Restoration',
	'23': 'Industry: Retail',
	'24': 'Industry: Book Publishing',
	'25': 'Industry: Gambling',
	'26': 'Sector: Manufacturing',
	'27': 'Government Size',
	'28': 'Welfare',
	'29': 'Public Healthcare',
	'30': 'Law Enforcement',
	'31': 'Business Subsidization',
	'32': 'Religiousness',
	'33': 'Income Equality',
	'34': 'Niceness',
	'35': 'Rudeness',
	'36': 'Intelligence',
	'37': 'Ignorance',
	'38': 'Political Apathy',
	'39': 'Health',
	'40': 'Cheerfulness',
	'41': 'Weather',
	'42': 'Compliance',
	'43': 'Safety',
	'44': 'Lifespan',
	'45': 'Ideological Radicality',
	'46': 'Defense Forces',
	'47': 'Pacifism',
	'48': 'Economic Freedom',
	'49': 'Taxation',
	'50': 'Freedom From Taxation',
	'51': 'Corruption',
	'52': 'Integrity',
	'53': 'Authoritarianism',
	'54': 'Youth Rebelliousness',
	'55': 'Culture',
	'56': 'Employment',
	'57': 'Public Transport',
	'58': 'Tourism',
	'59': 'Weaponization',
	'60': 'Recreational Drug Use',
	'61': 'Obesity',
	'62': 'Secularism',
	'63': 'Environmental Beauty',
	'64': 'Charmlessness',
	'65': 'Influence',
	'66': 'World Assembly Endorsements',
	'67': 'Averageness',
	'68': 'Human Development Index',
	'69': 'Primitiveness',
	'70': 'Scientific Advancement',
	'71': 'Inclusiveness',
	'72': 'Average Income',
	'73': 'Average Income Of Poor',
	'74': 'Average Income Of Rich',
	'75': 'Public Education',
	'76': 'Economic Output',
	'77': 'Crime',
	'78': 'Foreign Aid',
	'79': 'Black Market',
	'80': 'Residency',
	'81': 'Survivors',
	'82': 'Zombies',
	'83': 'Dead',
	'84': 'Percentage Zombies',
	'85': 'Average Disposable Income',
	'86': 'International Artwork',
	'87': 'Patriotism',
	'88': 'Food Quality'
};
