name: Deploy

on:
  push:
    branches: [vps-docker]
  pull_request:
    branches: [vps-docker]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd docker/hare
            git pull origin main
            git status
            docker compose up -d --build
